# NumPy

[NumPy](https://numpy.org/) is a fundamental tool to scientific computing.

In [14]:
import numpy as np

## Arrays

NumPy allows you to work with N-dimensional array objects.

### Create arrays

In [15]:
# Using a python list
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [16]:
# Using "arange" function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Using "zeros" function
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
# Using "ones" function
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
# Using "linspace" function
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Dimension of arrays

In [20]:
# Get the dimension of an array (one dimension)
one_dimension_array = np.array([1, 2, 3, 4, 5])
one_dimension_array.shape

(5,)

In [21]:
# Get the dimension of an array (two dimension)
two_dimension_array = np.array([[1, 2, 3, 4, 5]])
two_dimension_array.shape

(1, 5)

In [22]:
# Compare two arrays
np.array_equal(one_dimension_array, two_dimension_array)

False

In [23]:
# Reshape arrays
new_shape = (1, one_dimension_array.shape[0])
reshaped_array = one_dimension_array.reshape(new_shape)
reshaped_array

array([[1, 2, 3, 4, 5]])

In [24]:
# Compare two arrays
np.array_equal(reshaped_array, two_dimension_array)

True

### Slicing

In [25]:
# Create random three dimensional array
three_dimensional_array = np.random.rand(2, 3, 2)
three_dimensional_array

array([[[1.58550226e-01, 5.21199239e-01],
        [1.86042027e-01, 3.46493241e-01],
        [1.16632535e-02, 6.85605871e-01]],

       [[2.29623163e-04, 2.64774974e-01],
        [6.75114512e-01, 3.09988444e-01],
        [4.93028140e-01, 3.59521415e-01]]])

In [26]:
# Using slicing with int and [:] notation
three_dimensional_array[:1,1:,0]

array([[0.18604203, 0.01166325]])

### Arithmetic operations

In [34]:
array = np.arange(5)
print('array      =', array)
print('array + 5  =', array + 5)
print('array - 1  =', array - 1)
print('array / 5  =', array / 5)
print('array // 2 =', array // 2)
print('-array     =', -array)
print('array ** 2 =', array ** 2)
print('array % 2  =', array % 2)

array      = [0 1 2 3 4]
array + 5  = [5 6 7 8 9]
array - 1  = [-1  0  1  2  3]
array / 5  = [0.  0.2 0.4 0.6 0.8]
array // 2 = [0 0 1 1 2]
-array     = [ 0 -1 -2 -3 -4]
array ** 2 = [ 0  1  4  9 16]
array % 2  = [0 1 0 1 0]



| Operator | Universal functions (ufunc) |
| -------- | -------------------------- |
|``+``     | ``np.add()``               |
|``-``     | ``np.subtract()``          |
|``*``     | ``np.multiply()``          |

**Note**: Universal functions are executed using compiled C code.