# NumPy

[NumPy](https://numpy.org/) is a fundamental tool to scientific computing.

In [49]:
import numpy as np

## Arrays

NumPy allows you to work with N-dimensional array objects.

### Create arrays

In [50]:
# Using a python list
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [51]:
# Using "arange" function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# Using "zeros" function
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [53]:
# Using "ones" function
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
# Using "linspace" function
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Dimension of arrays

In [55]:
# Get the dimension of an array (one dimension)
one_dimension_array = np.array([1, 2, 3, 4, 5])
one_dimension_array.shape

(5,)

In [56]:
# Get the dimension of an array (two dimension)
two_dimension_array = np.array([[1, 2, 3, 4, 5]])
two_dimension_array.shape

(1, 5)

In [57]:
# Compare two arrays
np.array_equal(one_dimension_array, two_dimension_array)

False

In [58]:
# Reshape arrays
new_shape = (1, one_dimension_array.shape[0])
reshaped_array = one_dimension_array.reshape(new_shape)
reshaped_array

array([[1, 2, 3, 4, 5]])

In [59]:
# Compare two arrays
np.array_equal(reshaped_array, two_dimension_array)

True

### Slicing

In [60]:
# Create random three dimensional array
three_dimensional_array = np.random.rand(2, 3, 2)
three_dimensional_array

array([[[3.28955272e-01, 8.80285593e-01],
        [4.69612788e-01, 9.10412863e-01],
        [7.40779300e-01, 4.79061301e-01]],

       [[3.34017539e-01, 9.89761214e-01],
        [7.47489763e-01, 1.18592032e-01],
        [5.09170069e-01, 7.29388090e-04]]])

In [61]:
# Using slicing with int and [:] notation
three_dimensional_array[:1,1:,0]

array([[0.46961279, 0.7407793 ]])

### Arithmetic operations

In [62]:
array = np.arange(5)
print('array      =', array)
print('array + 5  =', array + 5)
print('array - 1  =', array - 1)
print('array / 5  =', array / 5)
print('array // 2 =', array // 2)
print('-array     =', -array)
print('array ** 2 =', array ** 2)
print('array % 2  =', array % 2)

array      = [0 1 2 3 4]
array + 5  = [5 6 7 8 9]
array - 1  = [-1  0  1  2  3]
array / 5  = [0.  0.2 0.4 0.6 0.8]
array // 2 = [0 0 1 1 2]
-array     = [ 0 -1 -2 -3 -4]
array ** 2 = [ 0  1  4  9 16]
array % 2  = [0 1 0 1 0]



| Operator | Universal functions (ufunc) |
| -------- | -------------------------- |
|``+``     | ``np.add()``               |
|``-``     | ``np.subtract()``          |
|``*``     | ``np.multiply()``          |

**Note**: Universal functions are executed using compiled C code.

In [63]:
# Other ufuncs
print(np.exp(array))                # Exponential
print(np.log(array))                # Natural logarithm
print(np.sqrt(array))               # Square root
print(np.greater(array, array))     # Greater

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[0.         1.         1.41421356 1.73205081 2.        ]
[False False False False False]


### Performance

In [64]:
%%timeit
array = np.arange(1000000)
zeros_array = np.zeros(1000000)

i = 0
for item in array:
    zeros_array[i] = item + item
    i += 1

209 ms ± 4.56 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [65]:
%%timeit
array + array

363 ns ± 3.28 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Statistics and randomness

In [66]:
array = np.arange(10)

print(np.mean(array))
print(np.median(array))
print(np.percentile(array, 40))
print(np.random.random(10))

4.5
4.5
3.6
[0.74718604 0.80396779 0.66900159 0.27971039 0.06131803 0.41389705
 0.46005109 0.23709932 0.81444187 0.60360689]
