# NumPy

[NumPy](https://numpy.org/) is a fundamental tool to scientific computing.

In [59]:
import numpy as np

## Arrays

NumPy allows you to work with N-dimensional array objects.

### Create arrays

In [60]:
# Using a python list
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [61]:
# Using "arange" function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# Using "zeros" function
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [63]:
# Using "ones" function
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
# Using "linspace" function
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Dimension of arrays

In [65]:
# Get the dimension of an array (one dimension)
one_dimension_array = np.array([1, 2, 3, 4, 5])
one_dimension_array.shape

(5,)

In [66]:
# Get the dimension of an array (two dimension)
two_dimension_array = np.array([[1, 2, 3, 4, 5]])
two_dimension_array.shape

(1, 5)

In [67]:
# Compare two arrays
np.array_equal(one_dimension_array, two_dimension_array)

False

In [68]:
# Reshape arrays
new_shape = (1, one_dimension_array.shape[0])
reshaped_array = one_dimension_array.reshape(new_shape)
reshaped_array

array([[1, 2, 3, 4, 5]])

In [69]:
# Compare two arrays
np.array_equal(reshaped_array, two_dimension_array)

True

### Slicing

In [72]:
# Create random three dimensional array
three_dimensional_array = np.random.rand(2, 3, 2)
three_dimensional_array

array([[[0.65085465, 0.23172832],
        [0.25821324, 0.82831371],
        [0.86560912, 0.41165905]],

       [[0.93139945, 0.76478715],
        [0.02043667, 0.98179204],
        [0.99082722, 0.81915868]]])

In [85]:
# Using slicing with int and [:] notation
three_dimensional_array[:1,1:,0]

array([[0.25821324, 0.86560912]])