# NumPy

[NumPy](https://numpy.org/) is a fundamental tool to scientific computing.

In [97]:
# Import library
import numpy as np

## Arrays

NumPy allows you to work with N-dimensional array objects.

### Create arrays

In [79]:
# Using a python list
np.array(object=[1, 2, 3, 4])

array([1, 2, 3, 4])

In [80]:
# Using "arange" function
np.arange(start=10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
# Using "zeros" function
np.zeros(shape=(2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [82]:
# Using "ones" function
np.ones(shape=(3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
# Using "linspace" function
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Dimension of arrays

In [84]:
# Get the dimension of an array (one dimension)
one_dimension_array = np.array(object=[1, 2, 3, 4, 5])
one_dimension_array.shape

(5,)

In [85]:
# Get the dimension of an array (two dimension)
two_dimension_array = np.array(object=[[1, 2, 3, 4, 5]])
two_dimension_array.shape

(1, 5)

In [86]:
# Compare two arrays
np.array_equal(a1=one_dimension_array, a2=two_dimension_array)

False

In [87]:
# Reshape arrays
new_shape = (1, one_dimension_array.shape[0])
reshaped_array = one_dimension_array.reshape(new_shape)
reshaped_array

array([[1, 2, 3, 4, 5]])

In [88]:
# Compare two arrays
np.array_equal(a1=reshaped_array, a2=two_dimension_array)

True

### Slicing

In [89]:
# Create random three dimensional array
three_dimensional_array = np.random.rand(2, 3, 2)
three_dimensional_array

array([[[0.70515405, 0.81089825],
        [0.89456756, 0.31277029],
        [0.77067591, 0.07898317]],

       [[0.06963977, 0.37185172],
        [0.91676208, 0.46179238],
        [0.5804499 , 0.60262179]]])

In [90]:
# Using slicing with int and [:] notation
three_dimensional_array[:1,1:,0]

array([[0.89456756, 0.77067591]])

### Arithmetic operations

In [91]:
array = np.arange(start=5)

print("array      =", array)
print("array + 5  =", array + 5)
print("array - 1  =", array - 1)
print("array / 5  =", array / 5)
print("array // 2 =", array // 2)
print("-array     =", -array)
print("array ** 2 =", array ** 2)
print("array % 2  =", array % 2)

array      = [0 1 2 3 4]
array + 5  = [5 6 7 8 9]
array - 1  = [-1  0  1  2  3]
array / 5  = [0.  0.2 0.4 0.6 0.8]
array // 2 = [0 0 1 1 2]
-array     = [ 0 -1 -2 -3 -4]
array ** 2 = [ 0  1  4  9 16]
array % 2  = [0 1 0 1 0]



| Operator | Universal functions (ufunc) |
| -------- | -------------------------- |
|``+``     | ``np.add()``               |
|``-``     | ``np.subtract()``          |
|``*``     | ``np.multiply()``          |

**Note**: Universal functions are executed using compiled C code.

In [92]:
# Other ufuncs
print(np.exp(array))                # Exponential
print(np.log(array))                # Natural logarithm
print(np.sqrt(array))               # Square root
print(np.greater(array, array))     # Greater

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[0.         1.         1.41421356 1.73205081 2.        ]
[False False False False False]


### Performance

In [93]:
%%timeit
array = np.arange(start=1000000)
zeros_array = np.zeros(shape=1000000)

i = 0
for item in array:
    zeros_array[i] = item + item
    i += 1

246 ms ± 3.15 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [94]:
%%timeit
array + array

391 ns ± 5.96 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Statistics and randomness

In [95]:
array = np.arange(start=10)

print(np.mean(a=array))
print(np.median(a=array))
print(np.percentile(a=array, q=40))
print(np.random.random(size=10))

4.5
4.5
3.6
[0.77365046 0.84302356 0.2555429  0.5318994  0.46716859 0.22768869
 0.15814208 0.90560498 0.34638337 0.97627776]
