# NumPy

[NumPy](https://numpy.org/) is a fundamental tool to scientific computing.

In [1]:
import numpy as np

## Arrays

NumPy allows you to work with N-dimensional array objects.

### Create arrays

In [2]:
# Using a python list
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
# Using "arange" function
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Using "zeros" function
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [5]:
# Using "ones" function
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# Using "linspace" function
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Dimension of arrays

In [7]:
# Get the dimension of an array (one dimension)
one_dimension_array = np.array([1, 2, 3, 4, 5])
one_dimension_array.shape

(5,)

In [8]:
# Get the dimension of an array (two dimension)
two_dimension_array = np.array([[1, 2, 3, 4, 5]])
two_dimension_array.shape

(1, 5)

In [9]:
# Compare two arrays
np.array_equal(one_dimension_array, two_dimension_array)

False

In [10]:
# Reshape arrays
new_shape = (1, one_dimension_array.shape[0])
reshaped_array = one_dimension_array.reshape(new_shape)
reshaped_array

array([[1, 2, 3, 4, 5]])

In [11]:
# Compare two arrays
np.array_equal(reshaped_array, two_dimension_array)

True

### Slicing

In [12]:
# Create random three dimensional array
three_dimensional_array = np.random.rand(2, 3, 2)
three_dimensional_array

array([[[0.63515796, 0.77051372],
        [0.19262872, 0.48117657],
        [0.33233748, 0.33576795]],

       [[0.37084233, 0.58662941],
        [0.56534024, 0.52532259],
        [0.65624327, 0.70750345]]])

In [13]:
# Using slicing with int and [:] notation
three_dimensional_array[:1,1:,0]

array([[0.19262872, 0.33233748]])

### Arithmetic operations

In [14]:
array = np.arange(5)
print('array      =', array)
print('array + 5  =', array + 5)
print('array - 1  =', array - 1)
print('array / 5  =', array / 5)
print('array // 2 =', array // 2)
print('-array     =', -array)
print('array ** 2 =', array ** 2)
print('array % 2  =', array % 2)

array      = [0 1 2 3 4]
array + 5  = [5 6 7 8 9]
array - 1  = [-1  0  1  2  3]
array / 5  = [0.  0.2 0.4 0.6 0.8]
array // 2 = [0 0 1 1 2]
-array     = [ 0 -1 -2 -3 -4]
array ** 2 = [ 0  1  4  9 16]
array % 2  = [0 1 0 1 0]



| Operator | Universal functions (ufunc) |
| -------- | -------------------------- |
|``+``     | ``np.add()``               |
|``-``     | ``np.subtract()``          |
|``*``     | ``np.multiply()``          |

**Note**: Universal functions are executed using compiled C code.

In [15]:
# Other ufuncs
print(np.exp(array))                # Exponential
print(np.log(array))                # Natural logarithm
print(np.sqrt(array))               # Square root
print(np.greater(array, array))     # Greater

[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[0.         1.         1.41421356 1.73205081 2.        ]
[False False False False False]


### Performance

In [16]:
%%timeit
array = np.arange(1000000)
zeros_array = np.zeros(1000000)

i = 0
for item in array:
    zeros_array[i] = item + item
    i += 1

267 ms ± 10.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
%%timeit
array + array

453 ns ± 14 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Statistics and randomness

In [18]:
array = np.arange(10)

print(np.mean(array))
print(np.median(array))
print(np.percentile(array, 40))
print(np.random.random(10))

4.5
4.5
3.6
[0.71917218 0.62322931 0.05091825 0.62256467 0.97585516 0.51035595
 0.67812138 0.85063778 0.81225542 0.77839264]
